### PR TITLE
add tbm support and fix c&p-bug

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Comment by gnzlbg** [comment]
@shepmaster would it be possible to do a minor release after merging this so that we can use it for testing in stdsimd?

**Comment by shepmaster** [comment]
Closing in favor of #12 — I strongly prefer separate commits for distinct changes.

**Comment by gnzlbg** [comment]
@shepmaster makes sense, sorry about that. Is there an easy way to split a commit with multiple changes into smaller commits with `git`? It seems that you did that pretty fast.

---

EDIT: ok seems that `git rebase -i` can do a lot of stuff I have no idea about. Will check that.

**Comment by shepmaster** [comment]
> ok seems that git rebase -i can do a lot of stuff I have no idea about

Yes, I probably spend about 50% of my time with git in `git rebase -i`, 45% in `git add -p`, and 5% in the rest. Those two commands allow me to organize my commits in a logical, story-like fashion.

**Pull request closed without merging**
